export const postConstant = {
  ERROR_API: 'ERROR_API',
  SAVE_INFO_POST: 'SAVE_INFO_POST',
  SAVE_URL_IMAGE: 'SAVE_URL_IMAGE',
  CLEAR_URL_IMAGE: 'CLEAR_URL_IMAGE',
  LOADING_UPLOAD_IMAGE: 'LOADING_UPLOAD_IMAGE',
};
